FROM golang:1.25 AS build

RUN apt-get update
WORKDIR /usr/local/src/aspace_publisher

COPY go.mod ./
COPY go.sum ./
RUN go mod download && go mod verify

COPY ./river_worker /usr/local/src/aspace_publisher/river_worker
COPY ./river_service/river_service.go /usr/local/src/aspace_publisher/main.go
COPY ./views /usr/local/src/aspace_publisher/views
COPY ./handlers /usr/local/src/aspace_publisher/handlers
COPY ./alma /usr/local/src/aspace_publisher/alma
COPY ./utils /usr/local/src/aspace_publisher/utils
COPY ./oclc /usr/local/src/aspace_publisher/oclc
COPY ./marc /usr/local/src/aspace_publisher/marc
COPY ./file /usr/local/src/aspace_publisher/file
COPY ./connect /usr/local/src/aspace_publisher/connect
COPY ./aw /usr/local/src/aspace_publisher/aw
COPY ./as /usr/local/src/aspace_publisher/as

RUN go build \
    -ldflags="-s -w" \
    -o /usr/local/src/aspace_publisher/river_server .

FROM golang:1.25

ARG USER_UID=1000
ARG USER_GID=1000

# Create non-root user
RUN groupadd --gid $USER_GID appuser && useradd --uid $USER_UID --gid appuser appuser

COPY --from=build /usr/local/src/aspace_publisher/river_server /aspace_publisher/river_server

USER appuser

EXPOSE 3200
ENTRYPOINT ["/aspace_publisher/river_server"]
