package alma

var bibstring_fixture1 = `<bib><suppress_from_publishing>true</suppress_from_publishing><suppress_from_external_search>true</suppress_from_external_search><record><leader>123</leader><controlfield tag="001">on1097882240</controlfield><controlfield tag="003">OCoLC</controlfield><datafield ind1="1" ind2=" " tag="774"><subfield code="t">Bridges of Lane County</subfield><subfield code="w">9999123456123</subfield></datafield><datafield ind1=" " ind2=" " tag="962"><subfield code="a">BoundWithRecord</subfield><subfield code="9">local</subfield></datafield></record></bib>`

var bibstring_fixture2 = `<bib><suppress_from_publishing>true</suppress_from_publishing><suppress_from_external_search>true</suppress_from_external_search><record><leader>123</leader><controlfield tag="001">on1097882240</controlfield><controlfield tag="003">OCoLC</controlfield><datafield ind1="1" ind2=" " tag="774"><subfield code="t">Bridges of Lane County</subfield><subfield code="w">9999123456123</subfield></datafield><datafield ind1="1" ind2=" " tag="774"><subfield code="t">Things to do when you are bored</subfield><subfield code="w">9999123456456</subfield></datafield><datafield ind1=" " ind2=" " tag="962"><subfield code="a">BoundWithRecord</subfield><subfield code="9">local</subfield></datafield></record></bib>`

var bibstring_fixture3 = `<?xml version=\"1.0\" encoding=\"UTF-8\"?><record><leader>456</leader><controlfield tag="001">on1097882242</controlfield><controlfield tag="003">OCoLC</controlfield><datafield ind1="1" ind2="0" tag="245"><subfield code="a">Things to do when you are bored</subfield></datafield></record>`

var bibstring_fixture4 = `<?xml version=\"1.0\" encoding=\"UTF-8\"?><record><leader>123</leader><controlfield tag="001">on1097882240</controlfield><controlfield tag="003">OCoLC</controlfield><datafield ind1="0" ind2=" " tag="041"><subfield code="a">eng</subfield></datafield><datafield ind1=" " ind2=" " tag="099"><subfield code="a">Coll 408</subfield></datafield></record>`

var bibstring_fixture5 = `<bib><suppress_from_publishing>false</suppress_from_publishing><suppress_from_external_search>true</suppress_from_external_search><record><leader>123</leader><controlfield tag="001">on1097882240</controlfield><controlfield tag="003">OCoLC</controlfield><datafield ind1="0" ind2=" " tag="041"><subfield code="a">eng</subfield></datafield><datafield ind1=" " ind2=" " tag="099"><subfield code="a">Coll 408</subfield></datafield></record></bib>`

var holdingstring_fixture1 = `<holding><suppress_from_publishing>false</suppress_from_publishing><record><leader>00000npcaa2200000 i 4500</leader><controlfield tag="008">240910i19752006xxu                 eng d</controlfield><datafield tag="852" ind1="8" ind2=" "><subfield code="b">SpecColl</subfield><subfield code="c">spmanus</subfield><subfield code="h">Coll 408</subfield></datafield><datafield tag="866" ind1="4" ind2="1"><subfield code="z">UNARRANGED COLLECTION UNAVAILABLE FOR USE. Inquiries regarding these materials should be submitted via the &lt;a href=&#39;https://library.uoregon.edu/scua/unprocessed-collections?title=1000-Friends-of-Oregon-records&amp;callnumber=Coll-408&#39; target=&#39;_blank&#39;&gt;Notice of Interest in Unprocessed Collections&lt;/a&gt;</subfield></datafield></record></holding>`

var itemstring_fixture1 = `{"holding_data":{"holding_id":"98765432987", "copy_id":"1"},"item_data":{"library":{"value":"SpecColl"},"location":{"value":"spmanus"},"barcode":"35025042674552","policy":{"value":"999"},"description":"Box 1","base_status":{"value":"1"},"physical_material_type":{"value":"MANUSCRIPT"}}}`

//based on fixture1 but with pid
var itemstring_fixture2 = `{"holding_data":{"holding_id":"98765432987", "copy_id":"1"},"item_data":{"pid":"456745674567","library":{"value":"SpecColl"},"location":{"value":"spmanus"},"barcode":"35025042674552","policy":{"value":"999"},"description":"Box 1","base_status":{"value":"1"},"physical_material_type":{"value":"MANUSCRIPT"}}}`
