package alma

var bibstring_fixture1 = `<bib><suppress_from_publishing>true</suppress_from_publishing><suppress_from_external_search>true</suppress_from_external_search><record><leader>123</leader><controlfield tag="001">on1097882240</controlfield><controlfield tag="003">OCoLC</controlfield><datafield ind1="1" ind2=" " tag="774"><subfield code="t">Bridges of Lane County</subfield><subfield code="w">9999123456123</subfield></datafield><datafield ind1=" " ind2=" " tag="962"><subfield code="a">BoundWithRecord</subfield><subfield code="9">local</subfield></datafield></record></bib>`

var bibstring_fixture2 = `<bib><suppress_from_publishing>true</suppress_from_publishing><suppress_from_external_search>true</suppress_from_external_search><record><leader>123</leader><controlfield tag="001">on1097882240</controlfield><controlfield tag="003">OCoLC</controlfield><datafield ind1="1" ind2=" " tag="774"><subfield code="t">Bridges of Lane County</subfield><subfield code="w">9999123456123</subfield></datafield><datafield ind1="1" ind2=" " tag="774"><subfield code="t">Things to do when you are bored</subfield><subfield code="w">999954325432</subfield></datafield><datafield ind1=" " ind2=" " tag="962"><subfield code="a">BoundWithRecord</subfield><subfield code="9">local</subfield></datafield></record></bib>`

var bibstring_fixture3 = `<?xml version=\"1.0\" encoding=\"UTF-8\"?><record><leader>456</leader><controlfield tag="001">on1097882242</controlfield><controlfield tag="003">OCoLC</controlfield><datafield ind1="1" ind2="0" tag="245"><subfield code="a">Things to do when you are bored</subfield></datafield></record>`

var bibstring_fixture4 = `<?xml version=\"1.0\" encoding=\"UTF-8\"?><record><leader>123</leader><controlfield tag="001">on1097882240</controlfield><controlfield tag="003">OCoLC</controlfield><datafield ind1="0" ind2=" " tag="041"><subfield code="a">eng</subfield></datafield><datafield ind1=" " ind2=" " tag="099"><subfield code="a">Coll 408</subfield></datafield></record>`

var bibstring_fixture5 = `<bib><suppress_from_publishing>false</suppress_from_publishing><suppress_from_external_search>true</suppress_from_external_search><record><leader>123</leader><controlfield tag="001">on1097882240</controlfield><controlfield tag="003">OCoLC</controlfield><datafield ind1="0" ind2=" " tag="041"><subfield code="a">eng</subfield></datafield><datafield ind1=" " ind2=" " tag="099"><subfield code="a">Coll 408</subfield></datafield></record></bib>`

var bibstring_fixture6 = `<bib><mms_id>654365436543</mms_id><suppress_from_publishing>false</suppress_from_publishing><suppress_from_external_search>true</suppress_from_external_search><record><leader>123</leader><controlfield tag="001">on1097882240</controlfield><controlfield tag="003">OCoLC</controlfield><datafield ind1="0" ind2=" " tag="041"><subfield code="a">eng</subfield></datafield><datafield ind1=" " ind2=" " tag="099"><subfield code="a">Coll 408</subfield></datafield></record></bib>`

// submit to post
var holdingstring_fixture1 = `<holding><suppress_from_publishing>false</suppress_from_publishing><record><leader>00000npcaa2200000 i 4500</leader><controlfield tag="008">240910i19752006xxu                 eng d</controlfield><datafield tag="852" ind1="8" ind2=" "><subfield code="b">SpecColl</subfield><subfield code="c">spmanus</subfield><subfield code="h">Coll 408</subfield></datafield><datafield tag="866" ind1="4" ind2="1"><subfield code="z">UNARRANGED COLLECTION UNAVAILABLE FOR USE. Inquiries regarding these materials should be submitted via the &lt;a href=&#39;https://library.uoregon.edu/scua/unprocessed-collections?title=1000-Friends-of-Oregon-records&amp;callnumber=Coll-408&#39; target=&#39;_blank&#39;&gt;Notice of Interest in Unprocessed Collections&lt;/a&gt;</subfield></datafield></record></holding>`

// after post, has holding id
var holdingstring_fixture2 = `<holding><holding_id>456745674567</holding_id><suppress_from_publishing>false</suppress_from_publishing><record><leader>00000npcaa2200000 i 4500</leader><controlfield tag="008">240910i19752006xxu                 eng d</controlfield><datafield tag="852" ind1="8" ind2=" "><subfield code="b">SpecColl</subfield><subfield code="c">spmanus</subfield><subfield code="h">Coll 408</subfield></datafield><datafield tag="866" ind1="4" ind2="1"><subfield code="z">UNARRANGED COLLECTION UNAVAILABLE FOR USE. Inquiries regarding these materials should be submitted via the &lt;a href=&#39;https://library.uoregon.edu/scua/unprocessed-collections?title=1000-Friends-of-Oregon-records&amp;callnumber=Coll-408&#39; target=&#39;_blank&#39;&gt;Notice of Interest in Unprocessed Collections&lt;/a&gt;</subfield></datafield></record></holding>`

// submit to put
var holdingstring_fixture3 = `<holding><holding_id>456745674567</holding_id><suppress_from_publishing>false</suppress_from_publishing><record><leader>00000npcaa2200000 i 4500</leader><controlfield tag="008">240910i19752006xxu                 eng d</controlfield><datafield tag="852" ind1="8" ind2=" "><subfield code="b">SpecColl</subfield>&lt;a href='https://scua.uoregon.edu/repositories/2/resources/1862' target='_blank'&gt;CONNECT TO THE ONLINE FINDING AID FOR THIS COLLECTION&lt;/a&gt;<subfield code="c">spmanus</subfield><subfield code="h">Coll 408</subfield></datafield><datafield tag="866" ind1="4" ind2="1"><subfield code="z"></subfield></datafield></record></holding>`

var itemstring_fixture1 = `{"holding_data":{"holding_id":"98765432987", "copy_id":"1"},"item_data":{"library":{"value":"SpecColl"},"location":{"value":"spmanus"},"barcode":"35025042674552","policy":{"value":"999"},"description":"Box 1","base_status":{"value":"1"},"physical_material_type":{"value":"MANUSCRIPT"}}}`

//based on fixture1 but with pid
var itemstring_fixture2 = `{"holding_data":{"holding_id":"98765432987", "copy_id":"1"},"item_data":{"pid":"456745674567","library":{"value":"SpecColl"},"location":{"value":"spmanus"},"barcode":"35025042674552","policy":{"value":"999"},"description":"Box 1","base_status":{"value":"1"},"physical_material_type":{"value":"MANUSCRIPT"}}}`

//based on fixture2 but with bib
var itemstring_fixture3 = `{"bib_data":{"mms_id": "1231231234"},"holding_data":{"holding_id":"98765432987", "copy_id":"1"},"item_data":{"pid":"456745674567","library":{"value":"SpecColl"},"location":{"value":"spmanus"},"barcode":"35025042674552","policy":{"value":"999"},"description":"Box 1","base_status":{"value":"1"},"physical_material_type":{"value":"MANUSCRIPT"}}}`

var itemstring_fixture4 = `{"bib_data":{"title":"Hunt. A Glance at the Past,","author":"Hunt,","mms_id":"99900464173201852","bib_suppress_from_publishing":"false","complete_edition":"","network_number":["(OCoLC)on1017491390","(OCoLC)1017491390","(EXLNZ-01ALLIANCE_NETWORK)99324529376301451"],"link":"https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs/99900464173201852"},"holding_data":{"holding_id":"22329204430001852","holding_suppress_from_publishing":"false","calculated_suppress_from_publishing":"false","permanent_call_number_type":{"value":"8","desc":"Other scheme"},"permanent_call_number":"CB H911","call_number_type":{"value":"8","desc":"Other scheme"},"call_number":"CB H911","accession_number":"","copy_id":"","in_temp_location":false,"temp_library":{},"temp_location":{},"temp_call_number_type":{"value":""},"temp_call_number":"","temp_call_number_source":"","temp_policy":{"value":""},"link":"https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs/99900464173201852/holdings/22329204430001852"},"item_data":{"pid":"23329204380001852","barcode":"ALMA300099","policy":{"value":"Unarranged","desc":"Unarranged"},"provenance":{"value":""},"description":"Unavailable Folder 1","library":{"value":"SpecColl","desc":"Special Collections and University Archives"},"location":{"value":"spmanus","desc":"Spec Coll manuscripts and archives"},"pages":"","pieces":"","requested":false,"creation_date":"2018-03-07Z","modification_date":"2026-04-27Z","base_status":{"value":"1","desc":"Item in place"},"awaiting_reshelving":false,"physical_material_type":{"value":"MANUSCRIPT","desc":"Manuscripts"},"po_line":"","year_of_issue":"","enumeration_a":"","enumeration_b":"","enumeration_c":"","enumeration_d":"","enumeration_e":"","enumeration_f":"","enumeration_g":"","enumeration_h":"","chronology_i":"","chronology_j":"","chronology_k":"","chronology_l":"","chronology_m":"","break_indicator":{"value":""},"pattern_type":{"value":""},"linking_number":"","type_of_unit":"","receiving_operator":"","process_type":{"value":""},"inventory_number":"","inventory_price":"","alternative_call_number":"","alternative_call_number_type":{"value":""},"storage_location_id":"","public_note":"","fulfillment_note":"","internal_note_1":"","internal_note_2":"","internal_note_3":"","statistics_note_1":"","statistics_note_2":"","statistics_note_3":"","physical_condition":{},"committed_to_retain":{},"retention_reason":{"value":""},"retention_note":""},"link":"https://api-na.hosted.exlibrisgroup.com/almaws/v1/bibs/99900464173201852/holdings/22329204430001852/items/23329204380001852"}`

//exists but pre-published version of fixture 2
var itemstring_fixture5 = `{"holding_data":{"holding_id":"98765432987", "copy_id":"1"},"item_data":{"pid":"456745674567","library":{"value":"SpecColl"},"location":{"value":"spmanus"},"barcode":"35025042674552","policy":{"value":"Unarranged"},"description":"Unavailable Box 1","base_status":{"value":"1"},"physical_material_type":{"value":"MANUSCRIPT"}}}`

var errstring_fixture1 = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><web_service_result xmlns="http://com/exlibris/urm/general/xmlbeans"><errorsExist>true</errorsExist><errorList><error><errorCode>401689</errorCode><errorMessage>No items found for barcode 1234567891.</errorMessage><trackingId>E01-1203204432-S0YS7-AWAE1544202929</trackingId></error></errorList></web_service_result>`
//end
